---
title: "TopoSpecies"
author: "Sylvain Schmitt"
date: "May 26, 2016"
output: html_document
---
# Data
```{r Data, echo=TRUE, message=FALSE, warning=FALSE}
rm(list = ls()); invisible(gc())
library(Uppangala)
library(raster)
Env <- genEnv()
Trees <- genTrees()
Species <- genSpecies()
Trees$SpCode <- as.factor(tolower(as.character(Trees$SpCode))) # Should be treated in gen functions
row.names(Species) <- tolower(row.names(Species))
Trees <- Trees[-which(is.na(Trees$X)),]
```

# Community definition
```{r Community}
com <- quadrats()
Trees$com <- NA
XY <- data.frame(X = Trees$X, Y = Trees$Y)
coordinates(XY) <- ~ X + Y
proj4string(XY) <- crs(com)
Trees$com <- (XY %over% com)[,1]
Trees$com[which(!is.na(Trees$com))] <- paste0('C', Trees$com[which(!is.na(Trees$com))])
```

# Adding topo to communities

```{r com topo, echo=TRUE, message=FALSE, warning=FALSE}
com@data$id <- paste0('C', com@data$id)
com@data$DEM <- extract(Env$DEM, as(com, "SpatialPolygons"), df = T, fun = mean)[,2]
Deriv <- DEMderiv(raster(com, 2), c('slope', 'curvature', 'aspect'))
com@data <- cbind(com@data, extract(Deriv, as(com, "SpatialPolygons"), df = T, fun = mean)[-1])
```

# Classes assignation
```{r Plot pop, echo=FALSE, fig.height=8, fig.width=9, message=FALSE, warning=FALSE}
com@data$topo <- as.factor(with(com@data, topo_classes(Slope, Curvature, Aspect)))
Trees$topo <- (XY %over% com)[,6]
```

# Species habitat association table
```{r Sp habitat table}
habitat_association <- data.frame(tapply(rep(1, length(Trees[,1])), list(Trees$SpCode, Trees$topo), sum))
habitat_association <- round(habitat_association / rowSums(habitat_association, na.rm = T) * 100)
habitat_association[is.na(habitat_association)] <- 0
knitr::kable(habitat_association)
```


# Species - Habitats plots
```{r Plot sp habitat, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE}
SpCode <- levels(Trees$SpCode)
col <- terrain.colors(7)[c(1,2,5,6,3,4)]
for(Sp in SpCode){
  main <- Sp
  if(Sp %in% row.names(Species)){
    main <- paste(Species[as.character(Sp),2], Species[as.character(Sp),3], sep = ', ')
  }
  plot(raster(com, 'topo'), col = col, main = main)
  # contour(Env$DEM, add = T)
  legend('bottomleft', fill = col, 
         legend = c(paste('Concave surface', habitat_association[Sp,1], '%'),
                    paste('Convex plane surface', habitat_association[Sp,2], '%'),
                    paste('North-East steep slope', habitat_association[Sp,3], '%'),
                    paste('South-West steep slope', habitat_association[Sp,4], '%'),
                    paste('North-East mean slope', habitat_association[Sp,5], '%'),
                    paste('South-West mean slope', habitat_association[Sp,6], '%')), cex = 0.7)
  points(Y ~ X, Trees[Trees$SpCode == Sp,], pch = 20)
}
```
