---
title: Decoupled wood and leaf strategies among canopy and understorey tree in a low-elevation rainforest of India
author: "Sylvain Schmitt, Maxime Réjou-Méchain, Valérie Raevel, Ayyappan N, Balachandran N., Barathan N., and François Munoz"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    number_sections: false
    toc: true
    toc_float: yes
  bookdown::word_document2: default
  bookdown::pdf_document2:
    includes:
      before_body: ./template/doc_prefix.tex
      in_header: ./template/preamble.tex
    number_sections: false
    toc: false
linestretch: 1.5
csl: mee.csl
bibliography: refs.bib
link-citations: yes
---

```{r config, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()); invisible(gc())
library(knitr)
library(parallel)
library(Uppangala)
library(raster)
library(broom)
library(vegan)
library(dplyr)
library(reshape2)
library(ggplot2)
library(ggfortify)
theme_set(bayesplot::theme_default())
cores <- detectCores() - 1
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 8,
  cache = T, cache.lazy = F)
cv <- function(x, na.rm = T)
  sd(x, na.rm = na.rm)/mean(x, na.rm = na.rm)
path <- '~/Documents/IFP/Uppangala/inst/doc/draft_save/'
n = 999 # Random repetitions
```

# Traits variation

```{r Traits}
kable(data.frame(
  Trait = c('Leaf thickness', 'Leaf area', 'Leaf dry matter content', 'Specific leaf area', 'Wood density'),
  Abbreviation = c('LT', 'LA', 'LDMC', 'SLA', 'WD'),
  Unit = c('$\\mu m$', '$mm^2$', '$mg.g^-1$', '$m^2.kg^-1$', '$g.cm^-3$'),
  Strategy = c('Leaf defense and investment',
        'Leaf resource capture vs.investment',
        'Leaf defense and investment',
        'Leaf resource acquisiton vs. defense',
        'Stem transport, structure and defense')
), caption = 'Functional traits measured. Traits with their abbreviation, standard unit, and associated species strategy for functioning, survival and reproduction [@baraloto_decoupled_2010].', format = 'pandoc')
```


```{r CV}
genPFT() %>% 
  select(-Tree, -Sp, -SpCode, -CE, -SHA, -LTD) %>% 
  melt(variable.name = 'trait') %>% 
  group_by(trait) %>% 
  summarise_each(funs(min(.,na.rm = T), max(., na.rm = T), 
                      mean(.,na.rm = T), sd(.,na.rm = T))) %>% 
  left_join(genPFT() %>% 
              select(-Sp, -SpCode, -CE, -SHA, -LTD) %>% 
              melt(id.vars = 'Tree', 
                   variable.name = 'trait', 
                   value.name = 'Intra-individuals') %>% 
              group_by(Tree, trait) %>% 
              summarise_each(funs(sd(., na.rm = T)/mean(., na.rm = T))) %>% 
              ungroup() %>% 
              select(-Tree) %>% 
              group_by(trait) %>% 
              summarise_each(funs(mean(., na.rm = T)))) %>% 
  left_join(genPFT() %>% 
              group_by(Tree, Sp, SpCode, CE) %>% 
              summarise_each(funs(mean)) %>% 
              ungroup() %>% 
              select(-Tree, -SpCode, -CE, -SHA, -LTD) %>% 
              melt(id.vars = 'Sp', 
                   variable.name = 'trait', value.name = 'Intra-species') %>% 
              group_by(Sp, trait) %>% 
              summarise_each(funs(sd(., na.rm = T)/mean(., na.rm = T))) %>% 
              ungroup() %>% 
              select(-Sp) %>% 
              group_by(trait) %>% 
              summarise_each(funs(mean(., na.rm = T)))) %>% 
  left_join(genPFT() %>% 
              group_by(Tree, Sp, SpCode, CE) %>% 
              summarise_each(funs(mean)) %>% 
              ungroup() %>% 
              select(-Tree, -CE) %>% 
              group_by(Sp, SpCode) %>% 
              summarise_each(funs(mean)) %>% 
              ungroup() %>% 
              select(-Sp, -SpCode, -SHA, -LTD) %>% 
              melt(variable.name = 'trait', value.name = 'Inter-species') %>% 
              group_by(trait) %>% 
              summarise_each(funs(sd(., na.rm = T)/mean(., na.rm = T)))) %>% 
  kable(digits = 2, caption = 'Intra-individual, intra-specific and inter-specific component of trait variation. The overall range, mean and standard deviation are provided for each trait. The remaining columns represent the coefficient of variation of trait values among leaves per individuals (intra-individual), among trees per species (intra-specific), and among trees of different species. See table \\@ref(tab:Traits) for abbreviation.', format = 'pandoc')
```

```{r Q}
# Sp level PFT
PFT <- genPFT() %>% 
  mutate(LA = log(LA)) %>% 
  mutate(SLA = log(SLA)) %>% 
  group_by(Tree, Sp, SpCode, CE) %>% 
  summarise_each(funs(mean(., na.rm = T))) %>% 
  ungroup() %>% 
  group_by(Sp, SpCode) %>% 
  summarise_each(funs(mean(., na.rm = T))) %>% 
  ungroup() %>% 
  select(-Tree, -Sp, -CE, -LTD, -SHA) %>% 
  filter(SpCode != "desi")
row.names(PFT) <- PFT$SpCode
# PCA
PFT.pca <- princomp(~ LA + WD + LT + LDMC + SLA, data = PFT, cor = T)
# Matrix Q
Q <- PFT %>% 
  left_join(data.frame(PFT.pca$scores) %>% mutate(SpCode = row.names(.))) %>% 
  rename(WES = Comp.1, LES = Comp.2) %>% 
  left_join(genSpecies()) %>% 
  mutate(strata = ifelse(Strata == 3, "U", "C")) %>%
  select(SLA, LDMC, WD, LA, LT, LES, WES, strata, SpCode) %>%
  mutate(strata = ifelse(SpCode == "agin", "U", strata))
```

```{r L}
com <- quadrats(cs = c(30,30))
XY <- genTrees()[c('x', 'y')]
coordinates(XY) <- ~ x + y
proj4string(XY) <- crs(com)
L <- genTrees() %>% 
  mutate(com = (XY %over% com)[,1]) %>% 
  filter(!is.na(com)) %>% 
  group_by(com, SpCode) %>% 
  summarise(n = n()) %>% 
  dcast(com ~ SpCode) %>% 
  replace(is.na(.), 0)
```

```{r R}
# Env <- genEnv()
# com <- quadrats(cs = c(30,30))
# com@data$Elevation <- extract(Env$DEM, as(com, "SpatialPolygons"), df = T, fun = mean)[,2]
# Deriv <- DEMderiv(raster(com, 'Elevation'), c('slope', 'curvature', 'plancurvature', 'profcurvature', 'cosaspect'), path = '/usr/share/applications')
# names(Deriv)[5] <- 'SW'
# com@data <- cbind(com@data, extract(Deriv, as(com, "SpatialPolygons"), df = T, fun = mean)[-1])
# com@data$Wetness <- extract(DEMderiv(Env$DEM, 'wetness'), as(com, "SpatialPolygons"), df = T, fun = mean)[,2]
# com@data$Canopy <- extract(Env$Canopy, as(com, "SpatialPolygons"), df = T, fun = mean)[,2]
# BA <- aggregate(Trees$Girth, list(Trees$com), function(x){sum(pi*(x/(2*pi))^2, na.rm = T)})
# com@data$BA <- BA$x[match(com@data$id, BA$Group.1)]
# pca.env <- princomp(~ Elevation + Slope + Curvature + PlanCurvature + ProfileCurvature + Wetness + SW, data = com@data, cor = T)
# save(pca.env, file = file.path(path, 'pca.env.Rdata'))
# R <- com@data[c('Slope', 'Curvature', 'Wetness', 'SW', 'Canopy', 'BA')]
# row.names(R) <- com@data$id
# R$community <- row.names(R)
# save(R, file = file.path(path, 'R.Rdata'))
load(file.path(path, 'R.Rdata'))
```

# Traits covariation

```{r PCA,  fig.cap='Principal Component Analysis (PCA) of species mean trait values. First axis, in red, is named wood economic spectrum (WES) ; whereas second axis, in green, is named leaf economic spectrum (LES). See table \\@ref(tab:Traits) for abbreviation.'}
autoplot(PFT.pca, 
         data = Q %>% 
           left_join(L %>% 
                       dplyr::select(-com) %>% 
                       summarise_all(sum) %>% 
                       t() %>% 
                       data.frame() %>% 
                       rename(abundance =  ".") %>% 
                       mutate(SpCode = row.names(.))) %>% 
           filter(!is.na(WES)), 
         colour = "strata",
         size = "abundance",
         loadings.label.size = 6,
         loadings.label.colour = 'black',
         loadings = T, loadings.label = T, loadings.colour = 'black',
         loadings.label.vjust = 1.2) +
  coord_equal() +
  geom_hline(aes(yintercept = 0, linetype = 'Wood'), 
             col = 'red') +
  geom_vline(aes(xintercept = 0, linetype = 'Leaf'), 
             col = 'green') +
  xlab('Axe 1 − 33.66 %') + ylab('Axe 2 − 29.07 %') +
  scale_linetype_manual(name = "Economics\nSpectrum", values = c(2, 2), 
                        guide = guide_legend(override.aes = 
                                               list(color = c("red", "green")))) +
  theme(legend.position = c(1, 1), 
        legend.justification = c(1, 1))
```

```{r varianceTest}
data <- Q %>% select(LES, WES, strata) %>% 
  melt(id.vars = "strata", variable.name = "spectrum")
# Q %>% 
#   select(LES, WES, strata) %>% 
#   melt(id.vars = "strata", variable.name = "spectrum") %>% 
#   group_by(strata) %>% 
#   do(var_test = car::leveneTest(value ~ spectrum, data = .)) %>% 
#   tidy(var_test)
data.frame(
  Variance_LES = c(var(data[data$strata == "C" & data$spectrum == "LES", "value"], na.rm = T),
                   var(data[data$strata == "U" & data$spectrum == "LES", "value"], na.rm = T)),
  Variance_WES = c(var(data[data$strata == "C" & data$spectrum == "WES", "value"], na.rm = T),
                   var(data[data$strata == "U" & data$spectrum == "WES", "value"], na.rm = T)),
  Bartlet_test = c(bartlett.test(value ~ spectrum, data[data$strata == "C",])$p.value,
                   bartlett.test(value ~ spectrum, data[data$strata == "U",])$p.value),
  Leven_test = c(car::leveneTest(value ~ spectrum, data[data$strata == "C",])$`Pr(>F)`[1],
                 car::leveneTest(value ~ spectrum, data[data$strata == "U",])$`Pr(>F)`[1]),
  row.names = c("Canopy", "Understorey")
) %>% kable(col.names = c("Variance of LES variance", "Variance of WES", 
                          "P-value of Bartlet's test", "P-value of Leven's test"),
            caption = "Test of variance differences betweenn guilds and economic spectra")
```

# Guilds hypervolume

```{r hypervolumes}
# library(hypervolume)
# bd <- Q %>% 
#   filter(!is.na(WES)) %>% 
#   select(-LES, -WES, -SpCode, -strata) %>% 
#   summarise_all(funs(sd)) %>% 
#   unlist()
# hv <- hypervolume_set(hypervolume(na.omit(Q[Q$strata == "C",names(bd)]), 
#                                   kde.bandwidth = bd, verbose = F), 
#                       hypervolume(na.omit(Q[Q$strata == "U",names(bd)]), 
#                                   kde.bandwidth = bd, verbose = F), 
#                       check.memory = F, verbose = F)
# plot(hv)
# rm(hv)
```

# Guilds functional differences

```{r percsign, fig.cap="Percentage of communities with indivdual traits significantly different between guilds (for canopy (C) and understorey (U) guilds). Test realized with an unpaired wilcoxon two sided test, significance was considered for p-values under the level $\\alpha = 0.05$ .See table \\@ref(tab:Traits) for abbreviations.", fig.height=4}
L %>% 
  rename(community = com) %>% 
  filter(!(community %in% c("C105", "C11",  "C26",  "C5" ))) %>% 
  melt(id.vars = "community", 
       variable.name = "SpCode",
       value.name = "abundance") %>% 
  filter(abundance > 0) %>% 
  tidyr::uncount(abundance) %>% 
  left_join(Q) %>% 
  select(-LES, -WES) %>% 
  melt(id.vars = c("community", "strata", "SpCode"),
       variable.name = "trait") %>% 
  filter(!is.na(value)) %>% 
  group_by(community, trait) %>% 
  do(wilcoxon = wilcox.test(value ~ strata, .)) %>% 
  tidy(wilcoxon) %>% 
  group_by(trait) %>% 
  summarise(n_sign = sum(p.value < 0.05), n = n()) %>% 
  mutate(n_perc = n_sign/n*100)  %>% 
  ggplot(aes(trait, n_perc)) +
  geom_bar(stat = "identity") +
  # coord_flip() +
  xlab("Functional trait") +
  ylab("Percentage of significant communities")
```

```{r GWMboxplot, fig.cap="Boxplot of guilds weighted means (GWM) among communties for each traits (for canopy (C) and understorey (U) guilds). See table \\@ref(tab:Traits) for abbreviations.", fig.height=4}
L %>%
  melt(id.var = "com",
       variable.name = "SpCode",
       value.name = "abundance") %>% 
  dcast(SpCode ~ com) %>% 
  left_join(Q) %>%
  select(-SpCode) %>%
  melt(id.vars = c('strata', 'LES', 'SLA', 'WES', 'WD', 'LDMC', 'LA', 'LT'),
       variable.name = 'community', value.name = 'abundance') %>%
  group_by(strata, community) %>%
  summarise_each(funs(weighted.mean(., abundance, na.rm = T)), -abundance) %>% 
  select(-community, -LES, -WES) %>% 
  melt(id.vars = "strata", 
       variable.name = "trait",
       value.name = "GWM") %>% 
  ggplot(aes(x = strata, y = GWM, fill = strata)) +
  geom_boxplot() +
  facet_wrap(~trait, scales = "free", nrow = 1) +
  xlab("Guild") + scale_fill_discrete(guide = "none") +
  ggpubr::stat_compare_means(aes(label = paste(..p.signif..))) 
```

# Environment effect on guilds

```{r GWMses}
GWM <- L %>%
  melt(id.var = "com",
       variable.name = "SpCode",
       value.name = "abundance") %>% 
  dcast(SpCode ~ com) %>% 
  left_join(Q) %>% 
  select(-SpCode) %>% 
  melt(id.vars = c('strata', 'LES', 'SLA', 'WES', 'WD', 'LDMC', 'LA', 'LT'),
       variable.name = 'community', value.name = 'abundance') %>% 
  group_by(strata, community) %>% 
  summarise_each(funs(weighted.mean(., abundance, na.rm = T)), -abundance)
nQ <- array(rep(as.matrix(Q), n),
            c(dim(Q), n),
            list(row.names(Q), names(Q), 1:n))
nQ <- array(apply(nQ, 3, function(x){
  x[which(x[,"strata"] == "C"),'SpCode'] <- sample(x[which(x[,"strata"] == "C"),'SpCode'])
  x[which(x[,"strata"] == "U"),'SpCode'] <- sample(x[which(x[,"strata"] == "U"),'SpCode'])
  return(x)
  }), c(dim(Q), n), list(row.names(Q), names(Q), 1:n))
cl <- makeCluster(cores)
clusterExport(cl, list('L', 'nQ'))
nGWM <- parApply(cl, nQ, 3, function(x){
  library(dplyr)
  library(reshape2)
  L %>%
    melt(id.var = "com",
         variable.name = "SpCode",
         value.name = "abundance") %>%
    dcast(SpCode ~ com) %>%
    left_join(data.frame(x)) %>%
    select(-SpCode) %>%
    melt(id.vars = c('strata', 'LES', 'SLA', 'WES', 'WD', 'LDMC', 'LA', 'LT'),
         variable.name = 'community', value.name = 'abundance') %>%
    group_by(strata, community) %>%
    mutate_each(funs(as.character), -abundance) %>%
    mutate_each(funs(as.numeric), -abundance) %>%
    summarise_each(funs(weighted.mean(., abundance, na.rm = T)), -abundance)
})
stopCluster(cl)
nGWM <- array(unlist(lapply(nGWM, function(x) as.matrix(x[3:9]))),
              c(dim(GWM[3:9]), n),
              list(row.names(GWM), names(GWM[3:9]), 1:n))
rm(cl, nQ)
save(nGWM, file = file.path(path, 'nGWM.Rdata'))
load(file.path(path, 'nGWM.Rdata'))
GWM_ses <- GWM
GWM_ses[3:9] <- (GWM[3:9] - apply(nGWM, 1:2, mean, na.rm = T))/apply(nGWM, 1:2, sd, na.rm = T)
```

```{r LM1}
GWM_ses %>% 
  filter(!is.na(strata)) %>% 
  melt(id.vars = c('strata', 'community')) %>% 
  rename(trait = variable) %>% 
  rename(SES = value) %>% 
  left_join(R) %>%
  group_by(strata, trait) %>% 
  do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + Canopy + BA, .), 
                     direction = 'both', trace = 0)) %>% 
  tidy(reg) %>% 
  group_by(strata, trait, term) %>%
  transmute(value = paste(format(estimate, scientific = T, digits = 2, trim = T), 
                          stars(p.value, ns = '   '))) %>% 
  dcast(strata + trait ~ term) %>% 
  select(strata, trait, Slope, Curvature, Wetness, SW, Canopy, BA) %>% 
  mutate_each(funs(replace(., is.na(.), ' '))) %>% 
  left_join( # Inclusion of R2 but should be split
    GWM_ses %>% 
      filter(!is.na(strata)) %>% 
      melt(id.vars = c('strata', 'community')) %>% 
      rename(trait = variable) %>% 
      rename(SES = value) %>% 
      left_join(R) %>%
      group_by(strata, trait) %>% 
      do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + Canopy + BA, .), 
                    direction = 'both', trace = 0)) %>% 
      glance(reg) %>% 
      select(r.squared) %>% 
      mutate(r.squared = round(r.squared, 2)) %>% 
      rename("$R^2$" = r.squared)
  )%>% # End of R2
  filter(trait != 'LES') %>% 
  filter(trait != 'WES') %>%
  bold() %>% 
  kable(caption = 'Linear models of the standardized effect size (SES) with null model NM2 for each trait of GWMs, for canopy (C) and understorey (U) guilds, in abundance. We performed stepwise selection of the predictors including slope, curvature, wetness southwesterness (SW), canopy height (Canopy) and basal area (BA), and only the selected predictors are shown. See table \\@ref(tab:Traits) for abbreviations. Bold and number of asterisk indicates the significance threshold ( * p-value<0.05, ** p-value <0.01, *** p-value<0.001).', format = 'pandoc')
```

```{r LM2}
GWM_ses %>% 
  filter(!is.na(strata)) %>% 
  melt(id.vars = c('strata', 'community')) %>% 
  rename(trait = variable) %>% 
  rename(SES = value) %>% 
  left_join(R) %>%
  group_by(strata, trait) %>% 
  do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + BA, .), 
                     direction = 'both', trace = 0)) %>% 
  tidy(reg) %>% 
  group_by(strata, trait, term) %>%
  transmute(value = paste(format(estimate, scientific = T, digits = 2, trim = T), 
                          stars(p.value, ns = '   '))) %>% 
  dcast(strata + trait ~ term) %>% 
  select(strata, trait, Slope, Curvature, Wetness, SW, BA) %>% 
  mutate_each(funs(replace(., is.na(.), ' '))) %>% 
  left_join( # Inclusion of R2 but should be split
    GWM_ses %>% 
      filter(!is.na(strata)) %>% 
      melt(id.vars = c('strata', 'community')) %>% 
      rename(trait = variable) %>% 
      rename(SES = value) %>% 
      left_join(R) %>%
      group_by(strata, trait) %>% 
      do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + BA, .), 
                    direction = 'both', trace = 0)) %>% 
      glance(reg) %>% 
      select(r.squared) %>% 
      mutate(r.squared = round(r.squared, 2)) %>% 
      rename("$R^2$" = r.squared)
  )%>% # End of R2
  filter(trait != 'LES') %>% 
  filter(trait != 'WES') %>%
  bold() %>% 
  kable(caption = 'Linear models of the standardized effect size (SES) with null model NM2 for each trait of GWMs, for canopy (C) and understorey (U) guilds, in abundance. We performed stepwise selection of the predictors including slope, curvature, wetness southwesterness (SW), canopy height (Canopy) and basal area (BA), and only the selected predictors are shown. See table \\@ref(tab:Traits) for abbreviations. Bold and number of asterisk indicates the significance threshold ( * p-value<0.05, ** p-value <0.01, *** p-value<0.001).', format = 'pandoc')
```

```{r LM3}
GWM_ses %>% 
  filter(!is.na(strata)) %>% 
  melt(id.vars = c('strata', 'community')) %>% 
  rename(trait = variable) %>% 
  rename(SES = value) %>% 
  left_join(R) %>%
  group_by(strata, trait) %>% 
  do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + Canopy, .), 
                     direction = 'both', trace = 0)) %>% 
  tidy(reg) %>% 
  group_by(strata, trait, term) %>%
  transmute(value = paste(format(estimate, scientific = T, digits = 2, trim = T), 
                          stars(p.value, ns = '   '))) %>% 
  dcast(strata + trait ~ term) %>% 
  select(strata, trait, Slope, Curvature, Wetness, SW, Canopy) %>% 
  mutate_each(funs(replace(., is.na(.), ' '))) %>% 
  left_join( # Inclusion of R2 but should be split
    GWM_ses %>% 
      filter(!is.na(strata)) %>% 
      melt(id.vars = c('strata', 'community')) %>% 
      rename(trait = variable) %>% 
      rename(SES = value) %>% 
      left_join(R) %>%
      group_by(strata, trait) %>% 
      do(reg = step(lm(SES ~ Slope + Curvature + Wetness + SW + Canopy, .), 
                    direction = 'both', trace = 0)) %>% 
      glance(reg) %>% 
      select(r.squared) %>% 
      mutate(r.squared = round(r.squared, 2)) %>% 
      rename("$R^2$" = r.squared)
  )%>% # End of R2
  filter(trait != 'LES') %>% 
  filter(trait != 'WES') %>%
  bold() %>% 
  kable(caption = 'Linear models of the standardized effect size (SES) with null model NM2 for each trait of GWMs, for canopy (C) and understorey (U) guilds, in abundance. We performed stepwise selection of the predictors including slope, curvature, wetness southwesterness (SW), canopy height (Canopy) and basal area (BA), and only the selected predictors are shown. See table \\@ref(tab:Traits) for abbreviations. Bold and number of asterisk indicates the significance threshold ( * p-value<0.05, ** p-value <0.01, *** p-value<0.001).', format = 'pandoc')
```

```{r WD, fig.cap='Standard effect size (SES) against curvature, for each trait and both guilds (canopy (C) and understorey (U) guilds). Each subplot show  standard effect size (SES) with null model NM12. Continuous line represents a null SES, whereas dashed line represents limits of the confidence interval above which SES are considered as significant. See table \\@ref(tab:Traits) for abbreviation.'}
GWM_ses %>%
  filter(!is.na(strata)) %>% 
  left_join(R) %>%
  ungroup() %>%
  select(strata, SLA, WD, LDMC, LA, LT, Curvature) %>%
  melt(id.vars = c('strata', 'Curvature'),
       variable.name = 'trait',
       value.name = 'SES') %>%
  ggplot(aes(Curvature, SES)) +
  geom_point() +
  facet_grid(strata ~ trait, scales = "free") +
  geom_hline(yintercept = c(0.95, -0.95), linetype = 'dashed') +
  geom_hline(yintercept = 0) 
```

# Environment selection

```{r PCAenv, fig.cap='Principal component analysis (PCA) performed on topgraphical variables. SW stand for southwesterness.'}
load(file.path(path, 'pca.env.Rdata'))
pca.env %>% 
  autoplot(colour = 'grey', loadings.label.size = 6,
           loadings.label.colour = 'black',
           loadings = T, loadings.label = T, 
           loadings.colour = 'black',
           loadings.label.vjust = 2) +
  coord_equal() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  geom_vline(xintercept = 0, linetype = 'dashed') +
  xlab('Axe 1 − 42.52 %') + ylab('Axe 2 − 23.44 %') 
```

