---
title: "Organisation des guildes autour d'axes de stratégies"
author: "Sylvain Schmitt sylvain.schmitt@agroparistech.fr"
date: '`r Sys.Date()`'
output:
  html_document: default
  pdf_document: default
csl: mee.csl
bibliography: refs.bib
---

```{r config, message=FALSE, warning=FALSE, include=FALSE}
rm(list = ls()) ; invisible(gc())
library(knitr)
library(parallel)
cores <- detectCores() - 1
library(Uppangala)
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 8, fig.width = 8,
  cache = T, cache.lazy = F)
```

Built with `Uppangala` package version `r packageVersion('Uppangala')`.

```{r data prep}
PFT <- genPFT()
# Individual aggregation
PFT_ind <- aggregate(PFT, by = list(PFT$Tree), FUN = mean, na.rm = T)
row.names(PFT_ind) <- PFT_ind$Group.1
SpT <- unique(PFT[1:2])
Sp <- SpT$Sp
names(Sp) <- SpT$Tree
SpCodeT <- unique(PFT[2:3])
SpCode <- SpCodeT$SpCode
names(SpCode) <- SpCodeT$Sp
CET <- unique(PFT[c(1,4)])
CE <- CET$CE
names(CE) <- CET$Tree
PFT_ind$Sp <- Sp[row.names(PFT_ind)]
PFT_ind$SpCode <- SpCode[as.character(PFT_ind$Sp)]
PFT_ind$CE <- CE[row.names(PFT_ind)]
PFT_ind <- PFT_ind[-c(1:2)]
PFT_ind$ID <- row.names(PFT_ind)
row.names(PFT_ind) <- PFT_ind$ID
PFT_ind <- PFT_ind[-which(names(PFT_ind) == 'ID')]
# Individual to log
PFT_ind$LA <- log(PFT_ind$LA)
PFT_ind$SLA <- log(PFT_ind$SLA)
PFT_ind$ID <- row.names(PFT_ind)
row.names(PFT_ind) <- PFT_ind$ID
PFT_ind <- PFT_ind[-which(names(PFT_ind) == 'ID')]
# Species aggregation
Species <- genSpecies()
PFT_sp <- aggregate(PFT_ind, by = list(PFT_ind$Sp), FUN = mean, na.rm = T)
row.names(PFT_sp) <- PFT_sp$Group.1
PFT_sp$SpCode <- SpCode[row.names(PFT_sp)]
PFT_sp <- PFT_sp[-c(1:2,4)]
sel <- which(Species$Strata[match(PFT_sp$SpCode, Species$SpCode)] == 3)
PFT_sp$strata <- NA
PFT_sp[-sel,'strata'] <- 'C'
PFT_sp[sel,'strata'] <- 'U'

rm(CET, PFT, SpCodeT, SpT, CE, sel)
```

```{r hypervolume overlap, echo=TRUE}
library(hypervolume)
set.seed(42)
n <- 99 # Random repetitions

# Data prep
data <- PFT_sp[-which(is.na(PFT_sp$WD)), c('LA', 'WD', 'LT', 'LDMC', 'SLA', 'strata')]
strata <- data$strata
data <- data[-6]
bd <- apply(PFT_ind[-which(is.na(PFT_ind$WD)), c('LA', 'WD', 'LT', 'LDMC', 'SLA')], 2, sd)

# Measurement
calcOverlap <- function(strata, data, bd){
  C <- hypervolume::hypervolume(data[strata == 'C',], bandwidth = bd, verbose = F)
  U <- hypervolume::hypervolume(data[strata == 'U',], bandwidth = bd, verbose = F)
  set <- hypervolume::hypervolume_set(C, U, check_memory = F, verbose = F)
  hypervolume::hypervolume_sorensen_overlap(set)
}
overlap <- calcOverlap(strata, data, bd)
cl <- makeCluster(cores)
clusterExport(cl, list('n', 'calcOverlap', 'strata', 'data', 'bd'))
nulloverlap <- parSapply(cl, 1:n, function(i) calcOverlap(sample(strata), data, bd))
stopCluster(cl) ; rm(cl)
```

```{r Result, echo=TRUE}
# Plot
pvalue <- (rank(c(overlap, nulloverlap))/(n+1))[1]
plot(density(nulloverlap), 
     main = paste('pvalue =', round(pvalue, 2)))
abline(v = overlap, lwd = 2, col = 'red')
```

```{r hypervolume specificity, echo=TRUE}
C <- hypervolume::hypervolume(data[strata == 'C',], bandwidth = bd, verbose = F, name = 'C')
U <- hypervolume::hypervolume(data[strata == 'U',], bandwidth = bd, verbose = F, name = 'U')
set <- hypervolume::hypervolume_set(C, U, check_memory = F, verbose = F)
Cu <- set@HVList$Unique_1
Uu <- set@HVList$Unique_2
Intersect <- set@HVList$Intersection
plot(hypervolume_join(Cu, Uu))
Spu <- list(C = data[hypervolume_inclusion_test(Cu, data),],
            Intersect = data[hypervolume_inclusion_test(Intersect, data),],
            U = data[hypervolume_inclusion_test(Uu, data),])
Spu$C <- Spu$C[-which(row.names(Spu$C) %in% row.names(Spu$Intersect)),]
Spu$U <- Spu$U[-which(row.names(Spu$U) %in% row.names(Spu$Intersect)),]
diff <- data.frame(N = unlist(lapply(Spu, function(x) dim(x)[1])),
                   Ntot = c(48, 78, 30),
                   Sp = unlist(lapply(Spu, function(x) paste0(row.names(x), collapse = ', '))))
kable(diff)
kable(do.call('rbind', lapply(Spu, function(x)apply(x, 2, mean))))
kable(do.call('rbind', lapply(Spu, function(x)apply(x, 2, var))))
```

